# ansible-playbook file: site.yml
#

#- name: Apply common configuration to all hosts  
#  hosts: all
#  remote_user: root
#
#  roles:

###
# admin.yml installs the admin node
- include: admin.yml
- include: install.yml
- include: login.yml
- include: grid.yml

