---

# network

admingroup: "admin"

external_interface: "eth0"
ext_net_addr: "193.166.3.128"
ext_ip_addr: "193.166.3.190"
ext_net_mask: "255.255.255.128"
ext_gateway: "193.166.3.254"

internal_interface: "eth1"
int_net_addr: "10.1.0.0"
int_ip_addr: "10.1.1.2"
int_net_mask: "255.255.0.0"
int_gateway: "10.1.1.4"

internal_net: "10.1.0.0/16"
internal_ip: "{{int_ip_addr}}"

# Kickstart file specifics

vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"

disks:
  - { path: "/var/vms/install.raw", size: 12 }
bridges:
  - br_ext
  - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "install"
fqdn: "{{siteName}}-install.{{siteDomain}}"
networks:
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --nameserver={{nameserver1}} --hostname={{ fqdn }} --gateway={{ext_gateway}} --noipv6"
#  - "network --onboot={{enable_int_nic}} --device={{internal_interface}} --bootproto=static --ip={{int_ip_addr}} --netmask={{int_net_mask}} --nodefroute --noipv6"
root_password: "{{ lookup('password', 'credentials/'+ inventory_hostname  +'_rootpw length=15') }}"

# Slurm
slurm_type: "service"

# SSHD
sshd:
 AllowGroups: "root admin" 

internal_net: "10.1.1.0/16" 

network_ether_interfaces:
  - device: "{{external_interface}}"
    bootproto: "static"
    onboot: "yes"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    defroute: "yes"
    nm_controlled: "no"
    type: "Ethernet"

  - device: "{{internal_interface}}"
    bootproto: "static"
    onboot: "yes"
    nm_controlled: "no"
    type: "Ethernet"

network_bridge_interfaces:
  - device: "br_ext"
    type: "Bridge"
    bootproto: "static"
    onboot: "yes"
    #stp: "on"
    address: "{{ext_ip_addr}}"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    ports: ["{{external_interface}}"]
    nm_controlled: "no"
    route:
      - network: "{{ext_net_addr}}"
        netmask: "{{ext_net_mask}}"
        gateway: "{{ext_gateway}}"

  - device: "br_int"
    type: "Bridge"
    bootproto: "static"
    onboot: "yes"
    #stp: "on"
    address: "{{int_ip_addr}}"
    netmask: "{{int_net_mask}}"
    ports: ["{{internal_interface}}"]
    nm_controlled: "no"

## DHCP_SERVER

dhcp_interfaces: "{{ internal_interface }}"
dhcp_common_domain: "fgi.csc.fi"
dhcp_common_nameservers: 193.166.4.24, 193.166.4.25
dhcp_common_default_lease_time: 600
dhcp_common_max_lease_time: 7200
dhcp_common_options: []
dhcp_common_parameters:
 - include "/etc/dhcp/dhcpd.d/ipxe.conf"
 - include "/etc/dhcp/dhcpd.d/nodes.conf"
dhcp_subnets:
 - base: 10.1.0.0
   netmask: "{{ int_net_mask }}"
#   routers: 10.1.1.2

dhcp_tftp_server_ip: "{{ int_ip_addr }}"

